// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7fd-jyR7SllxgkzUQ77DrMHc9dCIlxRY',
    appId: '1:935550430889:web:21e06fe66a6e115f6403b8',
    messagingSenderId: '935550430889',
    projectId: 'erasmusapp-e48f5',
    authDomain: 'erasmusapp-e48f5.firebaseapp.com',
    storageBucket: 'erasmusapp-e48f5.firebasestorage.app',
    measurementId: 'G-PZW37HZZCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-QTrh-gRQAofJDj46yCxIRkbcIWANXLg',
    appId: '1:935550430889:android:485a72a008b00c346403b8',
    messagingSenderId: '935550430889',
    projectId: 'erasmusapp-e48f5',
    storageBucket: 'erasmusapp-e48f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzSO0jkXiY9F7MhIM9Y16KPDeQ1ahkjl0',
    appId: '1:935550430889:ios:59ea8e1323fe85a26403b8',
    messagingSenderId: '935550430889',
    projectId: 'erasmusapp-e48f5',
    storageBucket: 'erasmusapp-e48f5.firebasestorage.app',
    iosBundleId: 'com.example.erasmusAppAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzSO0jkXiY9F7MhIM9Y16KPDeQ1ahkjl0',
    appId: '1:935550430889:ios:59ea8e1323fe85a26403b8',
    messagingSenderId: '935550430889',
    projectId: 'erasmusapp-e48f5',
    storageBucket: 'erasmusapp-e48f5.firebasestorage.app',
    iosBundleId: 'com.example.erasmusAppAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7fd-jyR7SllxgkzUQ77DrMHc9dCIlxRY',
    appId: '1:935550430889:web:eaee04573b17e0d06403b8',
    messagingSenderId: '935550430889',
    projectId: 'erasmusapp-e48f5',
    authDomain: 'erasmusapp-e48f5.firebaseapp.com',
    storageBucket: 'erasmusapp-e48f5.firebasestorage.app',
    measurementId: 'G-5NXPL9Q5VF',
  );
}
